{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dr-syncer.fullname" . }}-manager-rolebinding
  labels:
    {{- include "dr-syncer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dr-syncer.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name | default (include "dr-syncer.fullname" .) }}
  namespace: {{ .Release.Namespace }}

---
# Additional ClusterRoleBinding for destination cluster namespace management
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dr-syncer.fullname" . }}-destination-manager-rolebinding
  labels:
    {{- include "dr-syncer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dr-syncer.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name | default (include "dr-syncer.fullname" .) }}
  namespace: {{ .Release.Namespace }}
{{- end }}
