{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "dr-syncer.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dr-syncer.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dr-syncer.fullname" . }}-manager-role
  labels:
    {{- include "dr-syncer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "dr-syncer.io"
  resources:
  - replications
  - replications/status
  - replications/finalizers
  - remoteclusters
  - remoteclusters/status
  - remoteclusters/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  - secrets
  - services
  - persistentvolumeclaims
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - "/api"
  - "/api/*"
  - "/apis"
  - "/apis/*"
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dr-syncer.fullname" . }}-watcher-role
  namespace: {{ .Values.sourceNamespace | default .Release.Namespace }}
  labels:
    {{- include "dr-syncer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dr-syncer.fullname" . }}-manager-rolebinding
  labels:
    {{- include "dr-syncer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dr-syncer.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name | default (include "dr-syncer.fullname" .) }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dr-syncer.fullname" . }}-watcher-rolebinding
  namespace: {{ .Values.sourceNamespace | default .Release.Namespace }}
  labels:
    {{- include "dr-syncer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dr-syncer.fullname" . }}-watcher-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name | default (include "dr-syncer.fullname" .) }}
  namespace: {{ .Release.Namespace }}
---
# Additional ClusterRoleBinding for destination cluster namespace management
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dr-syncer.fullname" . }}-destination-manager-rolebinding
  labels:
    {{- include "dr-syncer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dr-syncer.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name | default (include "dr-syncer.fullname" .) }}
  namespace: {{ .Release.Namespace }}
{{- end }}
