{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dr-syncer.serviceAccountName" . }}
  labels:
    {{- include "dr-syncer.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dr-syncer.fullname" . }}-manager-role
  labels:
    {{- include "dr-syncer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "dr-syncer.io"
  resources:
  - replications
  - replications/status
  - replications/finalizers
  - remoteclusters
  - remoteclusters/status
  - remoteclusters/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dr-syncer.fullname" . }}-manager-rolebinding
  labels:
    {{- include "dr-syncer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dr-syncer.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "dr-syncer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
{{- if .Values.namespaceRBAC.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dr-syncer.fullname" . }}-namespace-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dr-syncer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - events
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dr-syncer.fullname" . }}-namespace-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dr-syncer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dr-syncer.fullname" . }}-namespace-role
subjects:
- kind: ServiceAccount
  name: {{ include "dr-syncer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
