{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dr-syncer.fullname" . }}-watcher-role
  namespace: {{ .Values.sourceNamespace | default .Release.Namespace }}
  labels:
    {{- include "dr-syncer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
{{- end }}
