{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "dr-syncer.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dr-syncer.labels" . | nindent 4 }}
{{- end }}
