apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: remoteclusters.dr-syncer.io
spec:
  group: dr-syncer.io
  names:
    kind: RemoteCluster
    listKind: RemoteClusterList
    plural: remoteclusters
    singular: remotecluster
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: RemoteCluster is the Schema for the remote clusters API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values.'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents.'
            type: string
          metadata:
            type: object
          spec:
            properties:
              kubeconfigSecretRef:
                description: KubeconfigSecretRef references a secret containing the kubeconfig for this cluster
                properties:
                  key:
                    description: Key is the key in the secret containing the kubeconfig
                    type: string
                  name:
                    description: Name is the name of the secret
                    type: string
                  namespace:
                    description: Namespace is the namespace of the secret
                    type: string
                required:
                - name
                - namespace
                type: object
              defaultSchedule:
                description: DefaultSchedule is the default schedule for replications using this cluster
                type: string
              defaultResourceTypes:
                description: DefaultResourceTypes is the default list of resource types to replicate
                items:
                  type: string
                type: array
            required:
            - kubeconfigSecretRef
            type: object
          status:
            properties:
              health:
                description: Health represents the current health status of the remote cluster connection
                type: string
              lastSyncTime:
                description: LastSyncTime is the last time the cluster was synced
                format: date-time
                type: string
              conditions:
                description: Conditions represent the latest available observations of the cluster's state
                items:
                  description: "Condition contains details for one aspect of the current state of this API Resource."
                  properties:
                    lastTransitionTime:
                      description: lastTransitionTime is the last time the condition transitioned from one status to another.
                      format: date-time
                      type: string
                    message:
                      description: message is a human readable message indicating details about the transition.
                      type: string
                    observedGeneration:
                      description: observedGeneration represents the .metadata.generation that the condition was set based upon.
                      format: int64
                      type: integer
                    reason:
                      description: reason contains a programmatic identifier indicating the reason for the condition's last transition.
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: type of condition in CamelCase.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - jsonPath: .status.health
      name: Health
      type: string
      description: Health status of the remote cluster connection
    - jsonPath: .status.lastSyncTime
      name: Last Sync
      type: date
      description: Time of last successful synchronization
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
